language: node_js
dist: xenial
node_js:
- 9
before_script:
- export TRAVIS_REPO_NAME=${TRAVIS_REPO_SLUG#*/}
- npm install -g decktape
script:
- sleep 2m
- decktape reveal http://www.spinw.org/$TRAVIS_REPO_NAME $TRAVIS_REPO_NAME.pdf
before_deploy:
- cp presentation_base/src/deploy.sh ./
deploy:
  provider: script
  script: bash ./deploy.sh
  skip_cleanup: true
  on:
    all_branches: true
env:
  global:
    secure: MNQ7dqFb6SJF0Ilz15YJ1qdjjmps9hM3JUpg7U+B6MLiwz7TEKDAHrOfjUsk39u+L3vAHzt4/YOi+DtCz8Q4Lr6h8wtLPu8F2Ce+eGIbJaTr819KUS4GELzGGLZSjEdOZCPj2YDdUmfdDBlvyfeGcylDIK62OmzmrO9YX7PEgzNJlMv6n81bkTxIRAKHq2oEBbfF14vyjIEDMudicUokxZZCuqCW7rIRlhVagjWJqAb4I4NHIxU4ZcT4iDehJEccWYAkDPWhgZwoAGB1e0Ii2m/N9MJbUjn4Gl6AHGR1iAzraQm01gXDFFc8PbfRM0aBuRF0bxlSjUgONO1AKMTxVJ3n6z7RHMiJD7+2okvqzlSz6MB+3iw5xD2zr1tELrAQIGyZ+nV9cIHCNyW1z6dHZpljnf7DU/EJNy/Unq2NYYmWczaUiXOcN4wGE5fdZlWREUb7GpNZ2JErv5gy3GtPCGwaipJVOTRvFfWQxjLBxhb8Fc91mAjtN/EHd8x1tqN2feepdXnIOOAEnwgQPeDHC3Xo5Mt/EV/7o0wlhTkcZ2GdIlw1j5C74pMcbnvPh+8Ijyhgiy8+lFZvA3FGzbCys5AmcAb1IiicJ6wbCb99PnMx+oSCTjHqnDOH4LaG6rryw0d0R3V2wjYo3Xx5dQ3cZSGezueZjI+ODXpFnKI8ciE=
